import { Photo } from './types';

export const samplePhotos: Photo[] = [
  {
    id: 'photo-1',
    url: '/Pics/Trees-Farewell-to-the Sun.jpg',
    title: 'Trees Farewell To The Sun',
    location: 'Unknown',
    photographer: 'Trees Farewell To The Sun',
    category: 'Forest',
  },
  {
    id: 'photo-2',
    url: '/Pics/Alpenglow.jpg',
    title: 'Alpenglow',
    location: 'Swiss Alps',
    photographer: 'Alpenglow',
    category: 'Mountain',
  },
  {
    id: 'photo-3',
    url: '/Pics/Bhaktapur-Temple.jpg',
    title: 'Bhaktapur Temple',
    location: 'Bhaktapur, Nepal',
    photographer: 'Bhaktapur Temple',
    category: 'City',
  },
  {
    id: 'photo-4',
    url: '/Pics/Bird-Sleep.jpg',
    title: 'Bird Sleep',
    location: 'Unknown',
    photographer: 'Bird Sleep',
    category: 'Sky',
  },
  {
    id: 'photo-5',
    url: '/Pics/Blossoms-Petals.jpg',
    title: 'Blossoms Petals',
    location: 'Unknown',
    photographer: 'Blossoms Petals',
    category: 'Forest',
  },
  {
    id: 'photo-6',
    url: '/Pics/Book-of-Lake.jpg',
    title: 'Book Of Lake',
    location: 'Unknown',
    photographer: 'Book Of Lake',
    category: 'Lake',
  },
  {
    id: 'photo-7',
    url: '/Pics/Cat-Liq.jpg',
    title: 'Cat Liq',
    location: 'Unknown',
    photographer: 'Cat Liq',
    category: 'City',
  },
  {
    id: 'photo-8',
    url: '/Pics/Cat-Staring.jpg',
    title: 'Cat Staring',
    location: 'Unknown',
    photographer: 'Cat Staring',
    category: 'City',
  },
  {
    id: 'photo-9',
    url: '/Pics/Cinematic-Plant.jpg',
    title: 'Cinematic Plant',
    location: 'Unknown',
    photographer: 'Cinematic Plant',
    category: 'Forest',
  },
  {
    id: 'photo-10',
    url: '/Pics/Cloud-Moon.jpg',
    title: 'Cloud Moon',
    location: 'Unknown',
    photographer: 'Cloud Moon',
    category: 'Sky',
  },
  {
    id: 'photo-11',
    url: '/Pics/Cloudy-Peak.jpg',
    title: 'Cloudy Peak',
    location: 'Unknown',
    photographer: 'Cloudy Peak',
    category: 'Mountain',
  },
  {
    id: 'photo-12',
    url: '/Pics/coconut.jpg',
    title: 'coconut',
    location: 'Tropical Island',
    photographer: 'coconut',
    category: 'Ocean',
  },
  {
    id: 'photo-13',
    url: '/Pics/Conquering-Mountain.jpg',
    title: 'Conquering Mountain',
    location: 'Himalayas',
    photographer: 'Conquering Mountain',
    category: 'Mountain',
  },
  {
    id: 'photo-14',
    url: '/Pics/Dark-Water.jpg',
    title: 'Dark-Water',
    location: 'Unknown',
    photographer: 'Dark Water',
    category: 'Lake',
  },
  {
    id: 'photo-15',
    url: '/Pics/Duck.jpg',
    title: 'Duck',
    location: 'Lake',
    photographer: 'Duck',
    category: 'Lake',
  },
  {
    id: 'photo-16',
    url: '/Pics/Farm-Voice.jpg',
    title: 'Farm Voice',
    location: 'Unknown',
    photographer: 'Farm Voice',
    category: 'Forest',
  },
  {
    id: 'photo-17',
    url: '/Pics/Fire.jpg',
    title: 'Fire',
    location: 'Unknown',
    photographer: 'Fire',
    category: 'Sky',
  },
  {
    id: 'photo-18',
    url: '/Pics/Flower-With-Fire.jpg',
    title: 'Flower With Fire',
    location: 'Unknown',
    photographer: 'Flower With Fire',
    category: 'Forest',
  },
  {
    id: 'photo-19',
    url: '/Pics/Frozen-Echo.jpg',
    title: 'Frozen Echo',
    location: 'Arctic Region',
    photographer: 'Frozen Echo',
    category: 'Forest',
  },
  {
    id: 'photo-20',
    url: '/Pics/Ghost-Rail.jpg',
    title: 'Ghost Rail',
    location: 'Old Railway',
    photographer: 'Ghost Rail',
    category: 'City',
  },
  {
    id: 'photo-21',
    url: '/Pics/Glacial-Monarch.jpg',
    title: 'Glacial Monarch',
    location: 'Antarctica',
    photographer: 'Glacial Monarch',
    category: 'Mountain',
  },
  {
    id: 'photo-22',
    url: '/Pics/Golden-Peak.jpg',
    title: 'Golden Peak',
    location: 'Himalayas',
    photographer: 'Golden Peak',
    category: 'Mountain',
  },
  {
    id: 'photo-23',
    url: '/Pics/Himalayan-Horizon.jpg',
    title: 'Himalayan Horizon',
    location: 'Himalayas',
    photographer: 'Himalayan Horizon',
    category: 'Mountain',
  },
  {
    id: 'photo-24',
    url: '/Pics/Kedarnath.jpg',
    title: 'Kedarnath',
    location: 'Kedarnath, India',
    photographer: 'Kedarnath',
    category: 'Mountain',
  },
  {
    id: 'photo-25',
    url: '/Pics/Lake-Sunset.jpg',
    title: 'Lake Sunset',
    location: 'Maldives',
    photographer: 'Lake Sunset',
    category: 'Lake',
  },
  {
    id: 'photo-26',
    url: '/Pics/Lake-of-Colors.jpg',
    title: 'Lake Of Colors',
    location: 'Switzerland',
    photographer: 'Lake Of Colors',
    category: 'Lake',
  },
  {
    id: 'photo-27',
    url: '/Pics/Lamp.jpg',
    title: 'Lamp',
    location: 'Unknown',
    photographer: 'Lamp',
    category: 'City',
  },
  {
    id: 'photo-28',
    url: '/Pics/Majestic-Gardens.jpg',
    title: 'Majestic Gardens',
    location: 'Unknown',
    photographer: 'Majestic Gardens',
    category: 'Forest',
  },
  {
    id: 'photo-29',
    url: '/Pics/Misty-mountain-valley.jpg',
    title: 'Misty Mountain Valley',
    location: 'Mountain Region',
    photographer: 'Misty Mountain Valley',
    category: 'Mountain',
  },
  {
    id: 'photo-30',
    url: '/Pics/Motion-Car.jpg',
    title: 'Motion Car',
    location: 'City',
    photographer: 'Motion Car',
    category: 'City',
  },
  {
    id: 'photo-31',
    url: '/Pics/Mountains-Vigil.jpg',
    title: 'Mountains Vigil',
    location: 'Himalayas',
    photographer: 'Mountains Vigil',
    category: 'Mountain',
  },
  {
    id: 'photo-32',
    url: '/Pics/Nepal-Cityscape.jpg',
    title: 'Nepal Cityscape',
    location: 'Nepal',
    photographer: 'Nepal Cityscape',
    category: 'City',
  },
  {
    id: 'photo-33',
    url: '/Pics/Rainbow.jpg',
    title: 'Rainbow',
    location: 'Unknown',
    photographer: 'Rainbow',
    category: 'Sky',
  },
  {
    id: 'photo-34',
    url: '/Pics/Rajasthan-Sunset.jpg',
    title: 'Rajasthan Sunset',
    location: 'Rajasthan, India',
    photographer: 'Rajasthan Sunset',
    category: 'Sky',
  },
  {
    id: 'photo-35',
    url: '/Pics/Silhouetted-Leaves.jpg',
    title: 'Silhouetted Leaves',
    location: 'Unknown',
    photographer: 'Silhouetted Leaves',
    category: 'Forest',
  },
  {
    id: 'photo-36',
    url: '/Pics/Sky-Thunder.jpg',
    title: 'Sky Thunder',
    location: 'Sky',
    photographer: 'Sky Thunder',
    category: 'Sky',
  },
  {
    id: 'photo-37',
    url: '/Pics/Sky-Converge.jpg',
    title: 'Sky Converge',
    location: 'Sky',
    photographer: 'Sky Converge',
    category: 'Sky',
  },
  {
    id: 'photo-38',
    url: '/Pics/Sky-Moon.jpg',
    title: 'Sky Moon',
    location: 'Sky',
    photographer: 'Sky Moon',
    category: 'Sky',
  },
  {
    id: 'photo-39',
    url: '/Pics/Sky.jpg',
    title: 'Sky',
    location: 'Sky',
    photographer: 'Sky',
    category: 'Sky',
  },
  {
    id: 'photo-40',
    url: '/Pics/Skyfall.jpg',
    title: 'Skyfall',
    location: 'Sky',
    photographer: 'Skyfall',
    category: 'Sky',
  },
  {
    id: 'photo-41',
    url: '/Pics/Spider.jpg',
    title: 'Spider',
    location: 'Unknown',
    photographer: 'Spider',
    category: 'Forest',
  },
  {
    id: 'photo-42',
    url: '/Pics/Stupa-Eye.jpg',
    title: 'Stupa Eye',
    location: 'Nepal',
    photographer: 'Stupa Eye',
    category: 'City',
  },
  {
    id: 'photo-43',
    url: '/Pics/Sun-Kissed-Horizon.jpg',
    title: 'Sun Kissed Horizon',
    location: 'Sunset',
    photographer: 'Sun Kissed Horizon',
    category: 'Sky',
  },
  {
    id: 'photo-44',
    url: '/Pics/Sunny-Shaam.jpg',
    title: 'Sunny Shaam',
    location: 'Maldives',
    photographer: 'Sunny Shaam',
    category: 'Ocean',
  },
  {
    id: 'photo-45',
    url: '/Pics/Twilight-Over-Waters.jpg',
    title: 'Twilight Over Waters',
    location: 'Ocean',
    photographer: 'Twilight Over Waters',
    category: 'Ocean',
  },
  {
    id: 'photo-46',
    url: '/Pics/Unknown-Foggy.jpg',
    title: 'Unknown Foggy',
    location: 'Unknown',
    photographer: 'Unknown Foggy',
    category: 'Sky',
  },
  {
    id: 'photo-47',
    url: '/Pics/Vibrant-Boat.jpg',
    title: 'Vibrant Boat',
    location: 'Lake',
    photographer: 'Vibrant Boat',
    category: 'Lake',
  },
  {
    id: 'photo-48',
    url: '/Pics/Warm-Tree.jpg',
    title: 'Warm Tree',
    location: 'Forest',
    photographer: 'Warm Tree',
    category: 'Forest',
  },
  {
    id: 'photo-49',
    url: '/Pics/Woodland-Glow.jpg',
    title: 'Woodland Glow',
    location: 'Forest',
    photographer: 'Woodland Glow',
    category: 'Forest',
  },
  {
    id: 'photo-50',
    url: '/Pics/Woodland-Walk.jpg',
    title: 'Woodland Walk',
    location: 'Forest',
    photographer: 'Woodland Walk',
    category: 'Forest',
  },
];
