import { Photo } from './types';

export const samplePhotos: Photo[] = [
  {
    id: 'photo-1',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734158159/FIERCEX/Alpenglow.jpg',
    title: 'Alpenglow',
    location: 'Swiss Alps',
    photographer: 'Alpenglow',
    category: 'Mountain',
  },
  {
    id: 'photo-2',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151868/FIERCEX/Bhaktapur-Temple.jpg',
    title: 'Bhaktapur Temple',
    location: 'Bhaktapur, Nepal',
    photographer: 'Bhaktapur Temple',
    category: 'City',
  },
  {
    id: 'photo-3',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734158153/FIERCEX/Blossoms-Petals.jpg',
    title: 'Blossoms Petals',
    location: 'Unknown',
    photographer: 'Blossoms Petals',
    category: 'Forest',
  },
  {
    id: 'photo-4',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151883/FIERCEX/Book-of-Lake.jpg',
    title: 'Book Of Lake',
    location: 'Unknown',
    photographer: 'Book Of Lake',
    category: 'Lake',
  },
  {
    id: 'photo-5',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734158143/FIERCEX/Shocked-Cat.jpg',
    title: 'Shocked Cat',
    location: 'Unknown',
    photographer: 'Cat Staring',
    category: 'City',
  },
  {
    id: 'photo-6',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151873/FIERCEX/Cinematic-Plant.jpg',
    title: 'Cinematic Plant',
    location: 'Unknown',
    photographer: 'Cinematic Plant',
    category: 'Forest',
  },
  {
    id: 'photo-7',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734158146/FIERCEX/Cloudy-Moon.jpg',
    title: 'Cloudy Moon',
    location: 'Unknown',
    photographer: 'Cloud Moon',
    category: 'Sky',
  },
  {
    id: 'photo-8',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151873/FIERCEX/Cloudy-Peak.jpg',
    title: 'Cloudy Peak',
    location: 'Unknown',
    photographer: 'Cloudy Peak',
    category: 'Mountain',
  },
  {
    id: 'photo-9',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151871/FIERCEX/Conquering-Mountain.jpg',
    title: 'Conquering Mountain',
    location: 'Himalayas',
    photographer: 'Conquering Mountain',
    category: 'Mountain',
  },
  {
    id: 'photo-10',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151878/FIERCEX/Dark-Water.jpg',
    title: 'Dark-Water',
    location: 'Unknown',
    photographer: 'Dark Water',
    category: 'Lake',
  },
  {
    id: 'photo-11',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151887/FIERCEX/Quacks-in-the-Eve.jpg',
    title: 'Quacks in the Eve',
    location: 'Lake',
    photographer: 'Duck',
    category: 'Lake',
  },
  {
    id: 'photo-12',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151884/FIERCEX/Farm-Voice.jpg',
    title: 'Farm Voice',
    location: 'Unknown',
    photographer: 'Farm Voice',
    category: 'Forest',
  },
  {
    id: 'photo-13',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151883/FIERCEX/Flower-With-Fire.jpg',
    title: 'Flower With Fire',
    location: 'Unknown',
    photographer: 'Flower With Fire',
    category: 'Forest',
  },
  {
    id: 'photo-14',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151882/FIERCEX/Frozen-Echo.jpg',
    title: 'Frozen Echo',
    location: 'Arctic Region',
    photographer: 'Frozen Echo',
    category: 'Forest',
  },
  {
    id: 'photo-15',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151884/FIERCEX/Ghost-Rail.jpg',
    title: 'Ghost Rail',
    location: 'Old Railway',
    photographer: 'Ghost Rail',
    category: 'City',
  },
  {
    id: 'photo-16',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/f_auto,q_auto/v1/FIERCEX/Glacial-Monarch',
    title: 'Glacial Monarch',
    location: 'Antarctica',
    photographer: 'Glacial Monarch',
    category: 'Mountain',
  },
  {
    id: 'photo-17',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734158144/FIERCEX/Golden-Peak.jpg',
    title: 'Golden Peak',
    location: 'Himalayas',
    photographer: 'Golden Peak',
    category: 'Mountain',
  },
  {
    id: 'photo-18',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151878/FIERCEX/Himalayan-Horizon.jpg',
    title: 'Himalayan Horizon',
    location: 'Himalayas',
    photographer: 'Himalayan Horizon',
    category: 'Mountain',
  },
  {
    id: 'photo-19',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151870/FIERCEX/Kedarnath.jpg',
    title: 'Kedarnath',
    location: 'Kedarnath, India',
    photographer: 'Kedarnath',
    category: 'Mountain',
  },
  {
    id: 'photo-20',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151878/FIERCEX/Lake-of-Colors.jpg',
    title: 'Lake Of Colors',
    location: 'Switzerland',
    photographer: 'Lake Of Colors',
    category: 'Lake',
  },
  {
    id: 'photo-21',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151881/FIERCEX/Majestic-Gardens.jpg',
    title: 'Majestic Gardens',
    location: 'Unknown',
    photographer: 'Majestic Gardens',
    category: 'Forest',
  },
  {
    id: 'photo-22',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151883/FIERCEX/Mysterious-Valley.jpg',
    title: 'Misty Mountain Valley',
    location: 'Mountain Region',
    photographer: 'Misty Mountain Valley',
    category: 'Mountain',
  },
  {
    id: 'photo-23',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151880/FIERCEX/Mountains-Vigil.jpg',
    title: 'Mountains Vigil',
    location: 'Himalayas',
    photographer: 'Mountains Vigil',
    category: 'Mountain',
  },
  {
    id: 'photo-24',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734158144/FIERCEX/Nepal-Cityscape.jpg',
    title: 'Nepal Cityscape',
    location: 'Nepal',
    photographer: 'Nepal Cityscape',
    category: 'City',
  },
  {
    id: 'photo-25',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151866/FIERCEX/A-Rainbows-Promise.jpg',
    title: 'A Rainbows Promise',
    location: 'Unknown',
    photographer: 'Rainbow',
    category: 'Sky',
  },
  {
    id: 'photo-26',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151891/FIERCEX/Thunder-Sky.jpg',
    title: 'Thunder Sky',
    location: 'Sky',
    photographer: 'Sky Thunder',
    category: 'Sky',
  },
  {
    id: 'photo-27',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151888/FIERCEX/Sky-Converge.jpg',
    title: 'Sky Converge',
    location: 'Sky',
    photographer: 'Sky Converge',
    category: 'Sky',
  },
  {
    id: 'photo-28',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151868/FIERCEX/Blue-Canvas.jpg',
    title: 'Blue Canvas',
    location: 'Sky',
    photographer: 'Sky Moon',
    category: 'Sky',
  },
  {
    id: 'photo-29',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151881/FIERCEX/Diamond-Dust.jpg',
    title: 'Diamond Dust',
    location: 'Sky',
    photographer: 'Diamond Dust',
    category: 'Sky',
  },
  {
    id: 'photo-30',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734158154/FIERCEX/Weaving-Web.jpg',
    title: 'Weaving Web',
    location: 'Unknown',
    photographer: 'Weaving Web',
    category: 'Forest',
  },
  {
    id: 'photo-31',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151892/FIERCEX/Stupa-Eye.jpg',
    title: 'Stupa Eye',
    location: 'Nepal',
    photographer: 'Stupa Eye',
    category: 'City',
  },
  {
    id: 'photo-32',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151894/FIERCEX/Sun-Kissed-Sea.jpg',
    title: 'Sun Kissed Sea',
    location: 'Sunset',
    photographer: 'Sun Kissed Sea',
    category: 'Sky',
  },
  {
    id: 'photo-33',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734158148/FIERCEX/Sunny-Shaam.jpg',
    title: 'Sunny Shaam',
    location: 'Maldives',
    photographer: 'Sunny Shaam',
    category: 'Ocean',
  },
  {
    id: 'photo-34',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151899/FIERCEX/Unknown-Foggy.jpg',
    title: 'Unknown Foggy',
    location: 'Unknown',
    photographer: 'Unknown Foggy',
    category: 'Sky',
  },
  {
    id: 'photo-35',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151899/FIERCEX/Vibrant-Boat.jpg',
    title: 'Vibrant Boat',
    location: 'Lake',
    photographer: 'Vibrant Boat',
    category: 'Lake',
  },
  {
    id: 'photo-36',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151900/FIERCEX/Warm-Tree.jpg',
    title: 'Warm Tree',
    location: 'Forest',
    photographer: 'Warm Tree',
    category: 'Forest',
  },
  {
    id: 'photo-37',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151901/FIERCEX/Woodland-Glow.jpg',
    title: 'Woodland Glow',
    location: 'Forest',
    photographer: 'Woodland Glow',
    category: 'Forest',
  },
  {
    id: 'photo-38',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151902/FIERCEX/Woodland-Walk.jpg',
    title: 'Woodland Walk',
    location: 'Forest',
    photographer: 'Woodland Walk',
    category: 'Forest',
  },
  {
    id: 'photo-39',
    url: 'https://res.cloudinary.com/dhsuepneb/image/upload/v1734151894/FIERCEX/Trees-Farewell-To-The-Sun.jpg',
    title: 'Trees Farewell To The-Sun',
    location: 'Forest',
    photographer: 'Lake View',
    category: 'Forest',
  },
];
